---
dependencies:
  - role: gccgo
    tags: golang
  - role: rvm_io.rvm1-ruby
    tags: ruby
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ansible_ssh_user}}/.rvm'
    rvm1_gpg_key_server: hkp://pgp.mit.edu
    rvm1_user: "{{ansible_ssh_user}}"
    rvm1_rubies:
    - "ruby-{{ruby_version}}"
