---

- gem: name=nats state=latest
  environment: ruby_environment

- name: Get bosh-init
  shell: "go get -d github.com/cloudfoundry/bosh-init"
  args: {creates: "{{go_path}}/src/github.com/cloudfoundry/bosh-init/"}
  environment: go_environment

- name: "Revert bosh-init (freeze the version to v0.0.43)"
  shell: "git checkout tags/v0.0.43"
  args: {chdir: "{{go_path}}/src/github.com/cloudfoundry/bosh-init/"}

- name: Build bosh-init
  shell: "./bin/build"
  args:
    chdir: "{{go_path}}/src/github.com/cloudfoundry/bosh-init/"
    creates: "{{go_path}}/src/github.com/cloudfoundry/bosh-init/out/bosh-init"
  environment: go_environment

- name: Add bosh-init path to $PATH
  file: "src={{go_path}}/src/github.com/cloudfoundry/bosh-init/out/bosh-init dest=/ state=link"
  args:
    chdir: "{{go_path}}/src/github.com/cloudfoundry/bosh-init/"
    creates: "{{go_path}}/src/github.com/cloudfoundry/bosh-init/out/bosh-init"


- name: Install CF CLI
  get_url: "url=https://cli.run.pivotal.io/stable?release=linux64-binary&source=github dest=/usr/local/bin/cf"
  sudo: yes
- file: path=/usr/local/bin/cf mode=755
  sudo: yes

- name: Install Spiff
  shell: "go get github.com/cloudfoundry-incubator/spiff"
  sudo: no
  environment: go_environment
  args:
    creates: "{{go_path}}/src/github.com/cloudfoundry-incubator/spiff"

