#!/bin/bash

cd /home/ubuntu/stemcell-builder
export base_os_image_path="/home/ubuntu/stemcell-builder/base-os-image-trusty-ppc64el.tar.gz"
bundle exec rake stemcell:build_os_image[ubuntu,trusty,$base_os_image_path]
env STEMCELL_BUILD_NUMBER=2905 bundle exec rake stemcell:build_with_local_os_image[openstack,kvm,ubuntu,trusty,go,/home/ubuntu/stemcell-builder/base-os-image-trusty-ppc64el.tar.gz]
