---
- name: Create folder for stemcell builder
  file: "dest={{stemcell_builder_path}} state=directory"

- name: Create bin folder for stemcell builder
  file: "dest={{stemcell_builder_path}}/bin state=directory"

- name: Put script file to the directory
  copy: "src=build-stemcell dest={{stemcell_builder_path}}/bin/build-stemcell mode=a+x"

- name: Put Gemfile to the directory
  copy: "src=Gemfile dest={{stemcell_builder_path}}/Gemfile"

# git clone --recursive --branch power-2915 https://github.com/Altoros/bosh.git
- name: "Check if {{stemcell_builder_path}}/bosh exists"
  stat: "path={{stemcell_builder_path}}/bosh"
  register: bosh_stemcell_folder

- name: Clone BOSH repo from Altoros github for stemcell builder
  git: "repo=https://github.com/Altoros/bosh.git"
  sudo: no
  args:
    dest: "{{stemcell_builder_path}}/bosh"
    version: power-2915
    recursive: yes
    accept_hostkey: yes
  register: result
  when: bosh_stemcell_folder.stat.exists == False
  until: not result|failed
  retries: 5

- name: Install BOSH gems
  shell: "bundle install"
  args:
    chdir: "{{stemcell_builder_path}}/bosh"
  sudo: no
  environment: ruby_environment
  register: result
  until: not result|failed
  retries: 5
