---
- name: Creates gccgo folder
  file: "path={{gcc_path}} state=directory"
  sudo: no

- name: Download GCC
  get_url: "url={{gcc_download_url}} dest={{gcc_archive_path}}"
  sudo: no

- name: Unarchive GCC
  unarchive: "src={{gcc_archive_path}} dest={{gcc_path}} copy=no creates={{gcc_path}}/gcc-{{gcc_version}}"
  sudo: no

- name: Rename folder with GCC sources
  command: "mv {{gcc_path}}/gcc-{{gcc_version}} {{gcc_source_path}} creates={{gcc_source_path}}"

- name: Creates gccgo build folder
  file: "path={{gcc_build_path}} state=directory"
  sudo: no

- name: Configure GCC
  sudo: no
  shell: >
    ../src/configure --enable-threads=posix --enable-shared --enable-__cxa_atexit \
      --enable-languages=c,c++,go --enable-secureplt --enable-checking=yes --with-long-double-128 \
      --enable-decimal-float --disable-bootstrap --disable-alsa --disable-multilib \
      --prefix=/usr/local/gccgo
    chdir={{gcc_build_path}}


- name: Run make
  sudo: no
  shell: "make chdir={{gcc_build_path}}"
    
- name: Run make
  sudo: yes
  shell: "make install chdir={{gcc_build_path}}"
