---
- name: Make the user sudoer with no password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ansible_ssh_user}}' line='%{{ansible_ssh_user}} ALL=(ALL) NOPASSWD: ALL'"
  sudo: yes

- name: Check kernel version
  shell: uname -r
  register: linux_version

- name: Install required packages
  sudo: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items: [
    "build-essential", "libgmp-dev", "libgmp3-dev", "libmpfr-dev", "libmpc-dev",
    "flex", "subversion", "git", "mercurial", "libsqlite3-dev", "lxc", "libffi-dev",
    "pandoc", "ruby", "ruby-dev", "curl", "aufs-tools", "btrfs-tools", "libdevmapper-dev",
    "libapparmor-dev"
  ]

- name: Install packages that depend on kernel version
  sudo: yes
  apt: "pkg=linux-image-extra-{{linux_version.stdout}} state=present update_cache=no"

- name: Install fpm gem
  gem: name=fpm version=1.3.3

