---
- name: Clone BOSH repo from Altoros github
  git: "repo=https://github.com/Altoros/bosh.git dest={{bosh_path}} accept_hostkey=yes version=power"
  sudo: no
  ignore_errors: True # this task can fail vecause local modifications will exist in the repo

- name: Prepare Bundler
  shell: "bundle config build.nokogiri '--use-system-libraries'"
  environment: ruby_environment

- name: Install BOSH gems
  shell: "bundle install"
  args:
    chdir: "{{bosh_path}}"
  sudo: no
  environment: ruby_environment
  ignore_errors: True # at this point it's not crucial