---
- name: Create folder for github projects
  file: "path={{github_path}} state=directory"

- name: Clone direnv
  git: "repo=https://github.com/zimbatm/direnv dest={{github_path}}/direnv accept_hostkey=yes"
  sudo: no

- name: Run make install for direnv
  shell: "make install chdir={{github_path}}/direnv creates=/usr/local/bin/direnv"
  sudo: yes

- file: path=/usr/local/bin/direnv mode=755
  sudo: yes
- shell: echo 'eval "$(direnv hook bash)"' >> /home/{{ansible_ssh_user}}/.bashrc
