---
- name: Create folder for github projects
  file: "path={{github_path}} state=directory"

- name: Clone direnv
  git: "repo=https://github.com/zimbatm/direnv dest={{github_path}}/direnv accept_hostkey=yes"
  sudo: no
  register: result
  until: not result|failed
  retries: 10

- name: Build direnv
  shell: "go build -o direnv chdir={{github_path}}/direnv creates={{github_path}}/direnv/direnv"
  sudo: no
  environment: go_environment
  register: result
  until: not result|failed
  retries: 5

- name: Copy direnv binary to /usr/local/bin
  shell: "cp {{github_path}}/direnv/direnv /usr/local/bin/direnv creates=/usr/local/bin/direnv"
  sudo: yes
  register: result
  until: not result|failed
  retries: 5

- name: Make direnv file executable
  file: path=/usr/local/bin/direnv mode=755
  sudo: yes
  register: result
  until: not result|failed
  retries: 5

- name: Add direnv load to .bashrc
  shell: echo 'eval "$(direnv hook bash)"' >> /home/{{ansible_ssh_user}}/.bashrc
  sudo: no
