---
- name: Clone BOSH repo from Altoros
  git: "repo=https://github.com/Altoros/bosh.git dest={{bosh_path}} accept_hostkey=yes branch=power"
  sudo: no

- name: Install BOSH gems
  shell: "bundle install"
  args:
    # creates: "{{bosh_path}}"
    chdir: "{{bosh_path}}"
  sudo: no
  environment: ruby_environment
