---
- name: Download Go
  sudo: yes
  get_url: "url=https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz dest=/opt/go{{go_version}}.linux-amd64.tar.gz"

- name: Untar Go
  shell: "tar -xzvf go{{go_version}}.linux-amd64.tar.gz"
  args: {chdir: "/opt", creates: "/opt/go"}
  sudo: yes

- name: Creates GOPATH
  file: "path=/home/{{username}}/go state=directory"
  sudo: no

- file: src=/opt/go/bin/go dest=/usr/bin/go state=link
  sudo: yes

- name: See if environment are set
  command: "grep GOROOT /home/{{username}}/.bashrc"
  register: goroot_variable_from_env
  ignore_errors: True

- name: Set environment variables
  shell: "echo '{{item}}' >> /home/{{username}}/.bashrc"
  with_items:
    - "export GOROOT=/opt/go"
    - "export GOPATH=/home/{{username}}/go"
    - "export PATH=$GOROOT/bin:$GOPATH/bin:$GOPATH/src/github.com/cloudfoundry/bosh-init/out:$PATH"
  when: (goroot_variable_from_env.stdout == "")
