---
- name: Clone BOSH repo from Altoros github
  git: "repo=https://github.com/Altoros/bosh.git dest={{bosh_path}} accept_hostkey=yes version=power"
  sudo: no

- debug: var=ruby_environment
- shell: "echo $PATH"
  environment: ruby_environment
  register: result
- debug: var=result


- name: Install BOSH gems
  shell: "bundle install"
  args:
    chdir: "{{bosh_path}}"
  sudo: no
  environment: ruby_environment
